#!/bin/bash

# Omarchy Dotfiles Installation Script
# Generated by Gemini CLI

set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$HOME/.config"
THEMES_DIR="$CONFIG_DIR/omarchy/themes"

echo "🚀 Starting Omarchy dotfiles restoration..."

# 1. Restore .config files
echo "📦 Restoring configuration files to $CONFIG_DIR..."
mkdir -p "$CONFIG_DIR"
cp -r "$DOTFILES_DIR/config/"* "$CONFIG_DIR/"

# 2. Restore home directory files
echo "🏠 Restoring home directory files..."
cp -r "$DOTFILES_DIR/home/".* "$HOME/" 2>/dev/null || true
cp "$DOTFILES_DIR/home/"* "$HOME/" 2>/dev/null || true

# 3. Restore themes from URLs
if [ -f "$DOTFILES_DIR/scripts/themes_urls.txt" ]; then
    echo "🎨 Restoring installed themes (this may take a while)..."
    mkdir -p "$THEMES_DIR"
    while IFS="|" read -r theme url; do
        if [ -n "$theme" ] && [ -n "$url" ]; then
            if [ ! -d "$THEMES_DIR/$theme" ]; then
                echo "📥 Cloning theme: $theme..."
                git clone --depth 1 "$url" "$THEMES_DIR/$theme" || echo "⚠️ Failed to clone $theme"
            else
                echo "✅ Theme $theme already exists, skipping."
            fi
        fi
    done < "$DOTFILES_DIR/scripts/themes_urls.txt"
fi

echo "✨ Restoration complete!"
echo "🔄 Running omarchy refresh to apply changes..."
omarchy refresh waybar || true
omarchy refresh walker || true
hyprctl reload || true

echo "🎉 Done! You might need to restart your session for some changes to take effect."
