accent = "#BF9769"
cursor = "#e9decb"
foreground = "#e9decb"
background = "#0b0904"
selection_foreground = "#0b0904"
selection_background = "#BF9769"

color0 = "#0b0904"
color1 = "#6C5232"
color2 = "#756247"
color3 = "#9B6840"
color4 = "#79895E"
color5 = "#BF9769"
color6 = "#D5B78B"
color7 = "#e9decb"
color8 = "#a39b8e"
color9 = "#6C5232"
color10 = "#756247"
color11 = "#9B6840"
color12 = "#79895E"
color13 = "#BF9769"
color14 = "#D5B78B"
color15 = "#e9decb"
