# Generado por theme-changer — no editar directamente
# Para personalizar colores: editar ~/.config/kitty/kitty.conf

foreground            #d3dae3
background            #282a33
selection_foreground  #282a33
selection_background  #2eb398
cursor                #2eb398
cursor_text_color     #282a33
url_color             #2eb398

# Terminal colors (0-7 normal, 8-15 bright)
color0   #303239
color1   #da4453
color2   #27ae60
color3   #fdbc4b
color4   #2980b9
color5   #bdc3c7
color6   #2eb398
color7   #666a73
color8   #2f343f
color9   #da4453
color10  #27ae60
color11  #fdbc4b
color12  #2eb398
color13  #da4453
color14  #2eb398
color15  #d3dae3

# Bordes
active_border_color   #2eb398
inactive_border_color #282a33
bell_border_color     #da4453
